version: "3.7"
services:
  db:
    image: chat/db
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
    ports:
      - ":5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - microservices-network
  server:
    image: chat/go
    depends_on:
      - db
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "chat"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "5432"
    ports:
      - "5000:5000"
    networks:
      - microservices-network

volumes:
  data:

networks:
  microservices-network:
    driver: bridge